In [1]:
import pandas as pd
import numpy as np

In [2]:
consumo_totale = pd.DataFrame(
    {"Total electricity consumption (TWh)": ["World", "North America", "United States", "Central and South America", "Europe", "Africa", "Middle East", "Asia Pacific", "China"],
    "2020": [269, 112, 108, 1.5, 57, 1.1, 1.1, 93, 62],
    "2023": [361, 158, 154, 1.5, 66, 1.3, 1.3, 128, 84],
    "2024": [416, 187, 183, 1.7, 68, 1.4, 1.5, 150, 102],
    "2030": [946, 434, 426, 3.3, 113, 2.9, 3, 378, 277]
})

consumo_totale

  Total electricity consumption (TWh)   2020   2023   2024   2030
0                               World  269.0  361.0  416.0  946.0
1                       North America  112.0  158.0  187.0  434.0
2                       United States  108.0  154.0  183.0  426.0
3           Central and South America    1.5    1.5    1.7    3.3
4                              Europe   57.0   66.0   68.0  113.0
5                              Africa    1.1    1.3    1.4    2.9
6                         Middle East    1.1    1.3    1.5    3.0
7                        Asia Pacific   93.0  128.0  150.0  378.0
8                               China   62.0   84.0  102.0  277.0

In [3]:
# IEA prevede, in caso di sviluppo accelerato, una crescita del consumo energetico in TWh da parte dei data center di circa il 203% dal 2024 al 2030
## Creo un nuova colonna in cui calcolo l'aumento percentuale

In [4]:
# seleziono la colonna '2024'
print(consumo_totale.iloc[:, 3])

# Calcolo l'aumento del consumo energetico del 203% dal 2024 al 2030
consumo_totale['2030'] = (consumo_totale['2024'] * 3.03846154)

# Calcolo l'aumento del 36% previsto per il 2035 (a partire dal 2030) e creo la nuova colonna
consumo_totale['2035'] = (consumo_totale['2030'] * 1.36)

consumo_totale

0    416.0
1    187.0
2    183.0
3      1.7
4     68.0
5      1.4
6      1.5
7    150.0
8    102.0
Name: 2024, dtype: float64

,Total electricity consumption (TWh),2020,2023,2024,2030,2035
0,World,269.0,361.0,416.0,1264.000001,1719.040001
1,North America,112.0,158.0,187.0,568.192308,772.741539
2,United States,108.0,154.0,183.0,556.038462,756.212308
3,Central and South America,1.5,1.5,1.7,5.165385,7.024923
4,Europe,57.0,66.0,68.0,206.615385,280.996923
5,Africa,1.1,1.3,1.4,4.253846,5.785231
6,Middle East,1.1,1.3,1.5,4.557692,6.198462
7,Asia Pacific,93.0,128.0,150.0,455.769231,619.846154
8,China,62.0,84.0,102.0,309.923077,421.495385

In [5]:
consumo_totale.to_csv("consumo_totale.csv", index = False)

In [6]:
llm = pd.DataFrame(
    {"Model": ["Gemma 2 2B", "Mistral 7B", "Phi 3 Small", "Llama 3.1 8B", "Phi 3 Mini", "Mistral Nemo", "Gemma 2 9B", "Phi 3 Medium", "Mixtral 8x7B", "Gemma 27B", "Llama 3.1 70B", "Mistral Large", "Mixtral 8x22B"],
     "Billions_of_parameters": [2, 7, 7, 8, 4, 12, 9, 14, 47, 27, 70, 123, 141],
     "Energy_in_Joules": [40.42, 43.76, 44.89, 51.12, 54.59, 66.71, 68.24, 96.26, 121.49, 192.55, 512.84, 869.17, 1161.61]
    }
)

llm

            Model  Billions_of_parameters  Energy_in_Joules
0      Gemma 2 2B                       2             40.42
1      Mistral 7B                       7             43.76
2     Phi 3 Small                       7             44.89
3    Llama 3.1 8B                       8             51.12
4      Phi 3 Mini                       4             54.59
5    Mistral Nemo                      12             66.71
6      Gemma 2 9B                       9             68.24
7    Phi 3 Medium                      14             96.26
8    Mixtral 8x7B                      47            121.49
9       Gemma 27B                      27            192.55
10  Llama 3.1 70B                      70            512.84
11  Mistral Large                     123            869.17
12  Mixtral 8x22B                     141           1161.61

In [7]:
llm.to_csv("consumo_modelli.csv", index = False)

In [9]:
llm_update= pd.DataFrame(
    {"Model": ["Gemma 2 2B", "Mistral 7B", "Phi 3 Small", "Llama 3.1 8B", "Phi 3 Mini", "Mistral Nemo", "Gemma 2 9B", "Phi 3 Medium", "Mixtral 8x7B", "Gemma 27B", "Llama 3.1 70B", "Mistral Large", "Mixtral 8x22B", "Grok-1", "Llama 3", "DeepSeek-V3"],
     "Billions_of_parameters": [2, 7, 7, 8, 4, 12, 9, 14, 47, 27, 70, 123, 141, 314, 405, 671],
     "Energy_in_Joules": [40.42, 43.76, 44.89, 51.12, 54.59, 66.71, 68.24, 96.26, 121.49, 192.55, 512.84, 869.17, 1161.61, 2373.44, 3067.25, 5095.30]
    }
)

llm_update

            Model  Billions_of_parameters  Energy_in_Joules
0      Gemma 2 2B                       2             40.42
1      Mistral 7B                       7             43.76
2     Phi 3 Small                       7             44.89
3    Llama 3.1 8B                       8             51.12
4      Phi 3 Mini                       4             54.59
5    Mistral Nemo                      12             66.71
6      Gemma 2 9B                       9             68.24
7    Phi 3 Medium                      14             96.26
8    Mixtral 8x7B                      47            121.49
9       Gemma 27B                      27            192.55
10  Llama 3.1 70B                      70            512.84
11  Mistral Large                     123            869.17
12  Mixtral 8x22B                     141           1161.61
13         Grok-1                     314           2373.44
14        Llama 3                     405           3067.25
15    DeepSeek-V3                     671           5095.30

In [10]:
llm_update.to_csv("llm_update.csv", index = False)

In [12]:
siti_minerari = pd.read_excel("/Users/jacopo/Desktop/Tesi Master/Dataset_da_analizzare/ICMM_siti_minerari.xlsx", sheet_name = "External")

# sostiuisco gli spazi nei nomi delle colonne con il trattino basso
siti_minerari.columns = siti_minerari.columns.str.replace(" ", "_")

siti_minerari

,ICMMID,Confidence_Factor,Mine_Name_,Group_Names,Latitude,Longitude,Asset_Type,Country_or_Region,Primary_Commodity,Secondary_Commodity,Other_Commodities
0,ICMM00026,Very Low,Pato,Pato;Pato Consolidated Dredging Co.,7.60535,-74.801100,Mine,Colombia,gold,silver,NaN
1,ICMM00027,Very Low,El Bagre,NaN,7.6087,-74.854700,Mine,Colombia,gold,silver,NaN
2,ICMM00033,Moderate,El Grillero,El Grillero;El Grillero,7.449165,-62.982965,Mine,Venezuela,gold,NaN,NaN
3,ICMM00034,Very Low,El Carmen,NaN,7.44314,-61.755800,Mine,Venezuela,gold,NaN,NaN
4,ICMM00038,Very Low,Santa Ana,Santa Ana;Mina A;La Loca;El Roble;Talisman,7.405424,-61.816220,Mine,Venezuela,gold,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...
8503,ICMM19859,Moderate,Jacurici Mine,Vale do Jacurici;Jacurici Mine;Mina De Ipueira...,-10.34199,-39.778190,Mine,Brazil,chromite,NaN,NaN
8504,ICMM20362,High,Fujian Yuanxin,Fujian Yuanxin,27.31193,118.825150,Mine,China,gold,silver,NaN
8505,ICMM20869,Moderate,Rudnik,Rudnik,44.13346,20.474400,Mine,Serbia,copper,lead,zinc
8506,ICMM21169,Moderate,Rio Jalan,Rio Jalan,14.60002,-86.183280,Mine,Honduras,gold,NaN,NaN
8507,ICMM21432,Moderate,Harmancik,Harmancik;HarmancÄ±k Plant;Hayri Ogelman Maden...,39.698823,29.103533,Mine;Plant,Turkey,chromite,chromium,NaN

In [13]:
print(siti_minerari.columns)

Index(['ICMMID', 'Confidence_Factor', 'Mine_Name_', 'Group_Names', 'Latitude',
       'Longitude', 'Asset_Type', 'Country_or_Region', 'Primary_Commodity',
       'Secondary_Commodity', 'Other_Commodities'],
      dtype='object')

In [14]:
# rimuovo le colonne superflue 
siti_minerari = siti_minerari.drop(columns = ["ICMMID", "Group_Names", "Latitude", "Longitude"])
siti_minerari

,Confidence_Factor,Mine_Name_,Asset_Type,Country_or_Region,Primary_Commodity,Secondary_Commodity,Other_Commodities
0,Very Low,Pato,Mine,Colombia,gold,silver,NaN
1,Very Low,El Bagre,Mine,Colombia,gold,silver,NaN
2,Moderate,El Grillero,Mine,Venezuela,gold,NaN,NaN
3,Very Low,El Carmen,Mine,Venezuela,gold,NaN,NaN
4,Very Low,Santa Ana,Mine,Venezuela,gold,NaN,NaN
...,...,...,...,...,...,...,...
8503,Moderate,Jacurici Mine,Mine,Brazil,chromite,NaN,NaN
8504,High,Fujian Yuanxin,Mine,China,gold,silver,NaN
8505,Moderate,Rudnik,Mine,Serbia,copper,lead,zinc
8506,Moderate,Rio Jalan,Mine,Honduras,gold,NaN,NaN
8507,Moderate,Harmancik,Mine;Plant,Turkey,chromite,chromium,NaN

In [15]:
# filtro i siti verificati (high confidence factor) di estrazione primaria di rame 
copper = siti_minerari[(siti_minerari["Primary_Commodity"] == "copper") & (siti_minerari["Confidence_Factor"] == "High")]
# seleziono solo le miniere 
copper_mine = copper[copper["Asset_Type"] == "Mine"]

# verifico la quantità di siti di estrazione di rame presenti nei paesi
copper_countries = copper_mine["Country_or_Region"].value_counts(dropna = True)
copper_countries

Country_or_Region
Chile                               30
United States                       19
China                               19
Democratic Republic of the Congo    17
Australia                           14
Mexico                              13
Russia                              11
Peru                                11
Kazakhstan                           9
Canada                               9
Zambia                               8
Brazil                               5
Spain                                4
Indonesia                            4
Philippines                          3
Poland                               3
New Caledonia                        2
Portugal                             2
Armenia                              2
Bulgaria                             2
Serbia                               2
Iran                                 2
Mongolia                             2
Panama                               2
Laos                                 2
Tajikistan                           1
Turkey                               1
Botswana                             1
Eritrea                              1
Ukraine                              1
India                                1
Sweden                               1
Finland                              1
Saudi Arabia                         1
Mauritania                           1
Argentina                            1
Namibia                              1
Papua New Guinea                     1
Ecuador                              1
Name: count, dtype: int64

In [82]:
# filtro i siti verificati (high confidence factor) di estrazione primaria di oro 
gold = siti_minerari[(siti_minerari["Primary_Commodity"] == "gold") & (siti_minerari["Confidence_Factor"] == "High")]
gold_mine = gold[gold["Asset_Type"] == "Mine"]

# verifico la quantità di siti di estrazione di oro presenti nei paesi
gold_countries = gold_mine["Country_or_Region"].value_counts(dropna = True)
gold_countries

Country_or_Region
Australia                           42
Canada                              31
United States                       30
Mexico                              25
South Africa                        23
Russia                              21
Brazil                              19
China                               16
Peru                                14
Ghana                               13
Burkina Faso                        12
Mali                                11
Argentina                           10
Indonesia                            8
Côte d'Ivoire                        7
New Caledonia                        7
Tanzania                             7
Chile                                6
Papua New Guinea                     5
Turkey                               4
Colombia                             4
Philippines                          4
Kazakhstan                           4
Kyrgyzstan                           3
Nicaragua                            3
Guatemala                            3
Namibia                              2
Mongolia                             2
Bulgaria                             2
Zimbabwe                             2
Guinea                               2
Senegal                              2
Suriname                             2
Honduras                             2
Finland                              2
Greece                               2
Guyana                               2
New Zealand                          2
Liberia                              1
Cambodia                             1
Ecuador                              1
Spain                                1
Sweden                               1
Mauritania                           1
Costa Rica                           1
Laos                                 1
Saudi Arabia                         1
Egypt                                1
Malaysia                             1
Dominican Republic                   1
Armenia                              1
Democratic Republic of the Congo     1
Nigeria                              1
Name: count, dtype: int64

In [88]:
# filtro i siti verificati (high confidence factor) di estrazione primaria di argento 
silver = siti_minerari[(siti_minerari["Primary_Commodity"] == "silver") & (siti_minerari["Confidence_Factor"] == "High")]
silver_mine = silver[silver["Asset_Type"] == "Mine"]

# verifico la quantità di siti di estrazione di ferro presenti nei argento
silver_countries = silver_mine["Country_or_Region"].value_counts(dropna = True)
silver_countries

Country_or_Region
Mexico           18
Peru             11
United States     4
Argentina         2
Canada            2
Russia            2
China             2
Morocco           2
Australia         1
Bolivia           1
Turkey            1
Name: count, dtype: int64

In [89]:
# filtro i siti verificati (high confidence factor) di estrazione primaria di argento 
lithium = siti_minerari[(siti_minerari["Primary_Commodity"] == "lithium") & (siti_minerari["Confidence_Factor"] == "High")]
lithium_mine = lithium[lithium["Asset_Type"] == "Mine"]

# verifico la quantità di siti di estrazione di ferro presenti nei argento
lithium_countries = lithium_mine["Country_or_Region"].value_counts(dropna = True)
lithium_countries

Country_or_Region
Australia        7
Argentina        5
Brazil           3
United States    3
Canada           3
China            3
New Caledonia    1
Zimbabwe         1
Ghana            1
Mali             1
Namibia          1
Chile            1
Portugal         1
Name: count, dtype: int64

In [91]:
# filtro i siti verificati (high confidence factor) di estrazione primaria di oro 
nickel = siti_minerari[(siti_minerari["Primary_Commodity"] == "nickel") & (siti_minerari["Confidence_Factor"] == "High")]
nickel_mine = nickel[nickel["Asset_Type"] == "Mine"]

# verifico la quantità di siti di estrazione di oro presenti nei paesi
nickel_countries = nickel_mine["Country_or_Region"].value_counts(dropna = True)
nickel_countries

Country_or_Region
Australia           8
Canada              5
Philippines         4
Indonesia           3
Finland             2
South Africa        2
Zambia              2
Brazil              2
Cuba                2
United States       1
New Caledonia       1
Papua New Guinea    1
Zimbabwe            1
Madagascar          1
Name: count, dtype: int64

In [17]:
ai_supercomp = pd.read_csv("/Users/jacopo/Desktop/Tesi Master/Dataset_da_analizzare/AI_supercomputers.csv")

ai_supercomp

,Name,Status,Certainty,Single cluster?,Max OP/s (log),H100 equivalents,Chip type (primary),Chip quantity (primary),Country,Owner,...,Cost Quote,Noteworthy,Decommissioned Date (if applicable),Largest existing cluster when first operational,% of largest cluster when first operational,Source 1,Source 2,Source 3,Source 4,Source 5
0,xAI 5 year plan,Planned,Unlikely,No,23.0,50025265.0,NaN,NaN,NaN,xAI,...,NaN,0 checked out of 1,NaN,NaN,NaN,https://archive.ph/RTF6i,NaN,NaN,NaN,NaN
1,Abu Dhabi UAE/USA 5GW Campus Phase 2,Planned,Likely,Unclear,22.6,20262759.0,NaN,NaN,United Arab Emirates,NaN,...,NaN,1 checked out of 1,NaN,NaN,NaN,https://web.archive.org/web/20250515200336/htt...,NaN,NaN,NaN,NaN
2,Meta $200B Campus Rumor,Planned,Unlikely,Yes,22.6,20262759.0,NaN,NaN,United States of America,Meta AI,...,$200B,0 checked out of 1,NaN,NaN,NaN,https://web.archive.org/web/20250226194100/htt...,NaN,NaN,NaN,NaN
3,DataVolt Neom 1.5 GW Phase 2,Planned,Likely,Unclear,22.0,5103588.0,NaN,NaN,Saudi Arabia,DataVolt,...,NaN,0 checked out of 1,NaN,NaN,NaN,http://web.archive.org/web/20250404231606/http...,NaN,NaN,NaN,NaN
4,Meta Louisiana Datacenter,Planned,Likely,Unclear,22.0,5103588.0,NaN,NaN,United States of America,Meta AI,...,NaN,0 checked out of 1,NaN,NaN,NaN,https://archive.ph/rS3ef,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
781,Anonymized Chinese System,Planned,Unlikely,Unclear,NaN,NaN,NaN,NaN,China,NaN,...,NaN,0 checked out of 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
782,Alibaba Cloud in Malaysia Phase 2,Existing,Confirmed,Yes,NaN,NaN,NaN,NaN,Malaysia,Alibaba,...,NaN,0 checked out of 1,NaN,NaN,NaN,https://www.alibabacloud.com/blog/alibaba-clou...,NaN,NaN,NaN,NaN
783,Anonymized Chinese System,Existing,Confirmed,Yes,NaN,NaN,NaN,500.0,China,NaN,...,NaN,0 checked out of 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
784,SoftBank Planned GB200,Planned,Likely,Yes,NaN,NaN,NVIDIA GB200,NaN,Japan,Softbank,...,NaN,0 checked out of 1,NaN,NaN,NaN,https://web.archive.org/web/20241116120654/htt...,NaN,NaN,NaN,NaN
785,Anonymized Chinese System,Planned,Likely,Yes,NaN,NaN,NaN,NaN,China,NaN,...,NaN,0 checked out of 1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
ai_supercomp.columns

Index(['Name', 'Status', 'Certainty', 'Single cluster?', 'Max OP/s (log)',
       'H100 equivalents', 'Chip type (primary)', 'Chip quantity (primary)',
       'Country', 'Owner', 'First Operational Date', 'Note', 'Sector',
       'Power Capacity (MW)', 'Hardware Cost', 'Location', 'Users',
       'Hardware note', 'Quote', 'First Operational Date Note',
       'Certainty Note', 'Energy Efficiency (log)', 'Builds Upon',
       'Superseded by', 'Possible Duplicate', 'Possible Duplicate Of',
       'Chip type (secondary)', 'Chip quantity (secondary)',
       'Total number of AI chips', 'GPU Supplier (primary)',
       'GPU supplier (secondary)', 'Include in Standard Analysis', 'Exclude',
       'Rank when first operational', '16-bit OP/s (log)', 'Max OP/s',
       '8-bit OP/s', '16-bit OP/s', '32-bit OP/s',
       'Calculated Power Capacity (MW)', 'Reported Power Capacity (MW)',
       'Energy Efficiency', 'Calculated Cost', 'Reported Cost',
       'Reported Cost (Inflation adjusted)', 'Cost Quote', 'Noteworthy',
       'Decommissioned Date (if applicable)',
       'Largest existing cluster when first operational',
       '% of largest cluster when first operational', 'Source 1', 'Source 2',
       'Source 3', 'Source 4', 'Source 5'],
      dtype='object')

In [5]:
new_supercomp = ai_supercomp[["Name", "Status", "Owner", "First Operational Date" , "Total number of AI chips"]]

# filtro solo le strutture esistenti e rimuovo le righe vuote del numero totale di chip per l'IA
new_supercomp = new_supercomp[(new_supercomp["Status"] != "Planned") & (new_supercomp["Total number of AI chips"].notna())]

# rimuovo le righe con valori vuoti
new_supercomp = new_supercomp[new_supercomp["First Operational Date"].notna()]

# modifico le righe vuote della colonna "Owner"
new_supercomp["Owner"] = new_supercomp["Owner"].fillna("Not specified")

new_supercomp

,Name,Status,Owner,First Operational Date,Total number of AI chips
25,xAI Colossus Memphis Phase 3,Existing,xAI,2025-07-22,230000.0
30,xAI Colossus Memphis Phase 2,Existing,xAI,2025-02-18,200000.0
42,xAI Colossus Memphis Phase 1,Existing,xAI,2024-09-02,100000.0
44,Meta 100k,Existing,Meta AI,2024-10-30,100000.0
45,OpenAI/Microsoft Goodyear Arizona,Existing,"Microsoft,OpenAI",2024-10-02,100000.0
...,...,...,...,...,...
714,Anonymized Chinese System,Existing,Not specified,2023-04-15,2000.0
724,Anonymized Chinese System,Existing,Not specified,2023-04-15,7000.0
763,Anonymized Chinese System,Existing,Not specified,2013-07-15,50000.0
780,Anonymized Chinese System,Existing,Not specified,2023-12-15,200000.0
783,Anonymized Chinese System,Existing,Not specified,2018-07-15,500.0

In [6]:
new_supercomp = new_supercomp.sort_values(by=['First Operational Date'], ascending = True)

new_supercomp

,Name,Status,Owner,First Operational Date,Total number of AI chips
699,Anonymized Chinese System,Existing,Not specified,2010-11-15,7000.0
702,Anonymized Chinese System,Existing,Not specified,2011-11-15,2000.0
662,Anonymized Chinese System,Existing,Not specified,2012-03-15,3000.0
575,Oak Ridge NL Titan,Decommissioned,US Department of Energy,2012-10-29,18688.0
763,Anonymized Chinese System,Existing,Not specified,2013-07-15,50000.0
...,...,...,...,...,...
198,AIST ABCI-Q,Existing,National Institute of Advanced Industrial Scie...,2025-06-15,2048.0
130,University of Bristol Isambard-AI,Existing,UK Research and Innovation,2025-06-15,5448.0
338,Core42 AI-03,Existing,G42,2025-06-15,4320.0
187,CEA EXA1-HE Phase 3,Existing,French Alternative Energies and Atomic Energy ...,2025-06-15,2688.0
25,xAI Colossus Memphis Phase 3,Existing,xAI,2025-07-22,230000.0

In [7]:
new_supercomp = pd.DataFrame(new_supercomp)

In [8]:
# converto la colonna 'First Operational Date' in formato data
new_supercomp['First Operational Date'] = pd.to_datetime(new_supercomp['First Operational Date'])

# creo la colonna 'Year' e sommo il numero di chip IA resi operativi per ogni anno 
new_supercomp['Year'] = new_supercomp['First Operational Date'].dt.year
chips_per_year = new_supercomp.groupby('Year')['Total number of AI chips'].sum()

In [9]:
chips_per_year

Year
2010       7000.0
2011       2000.0
2012      21688.0
2013      50000.0
2014      11384.0
2015       4160.0
2016       9232.0
2017     101068.0
2018      80774.0
2019      63844.0
2020     151087.0
2021     200480.0
2022     247690.0
2023     611988.0
2024    1080808.0
2025     573701.0
Name: Total number of AI chips, dtype: float64

In [132]:
chips_per_year.to_csv("chips_per_year.csv")

In [2]:
fao_stat = pd.read_csv("/Users/jacopo/Desktop/Tesi Master/Dataset_da_analizzare/fao_stat.csv")

fao_stat

,Domain Code,Domain,Area Code (M49),Area,Element Code,Element,Item Code,Item,Year Code,Year,Unit,Value,Flag,Flag Description
0,GPP,Emissions from pre and post agricultural produ...,2,Africa,723113,Emissions (CO2eq) (AR5),6504,Fertilizers Manufacturing,1990,1990,kt,895.658805,E,Estimated value
1,GPP,Emissions from pre and post agricultural produ...,2,Africa,723113,Emissions (CO2eq) (AR5),6504,Fertilizers Manufacturing,1991,1991,kt,982.244281,E,Estimated value
2,GPP,Emissions from pre and post agricultural produ...,2,Africa,723113,Emissions (CO2eq) (AR5),6504,Fertilizers Manufacturing,1992,1992,kt,1058.338629,E,Estimated value
3,GPP,Emissions from pre and post agricultural produ...,2,Africa,723113,Emissions (CO2eq) (AR5),6504,Fertilizers Manufacturing,1993,1993,kt,1503.701892,E,Estimated value
4,GPP,Emissions from pre and post agricultural produ...,2,Africa,723113,Emissions (CO2eq) (AR5),6504,Fertilizers Manufacturing,1994,1994,kt,2000.607434,E,Estimated value
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1831,GPP,Emissions from pre and post agricultural produ...,9,Oceania,723113,Emissions (CO2eq) (AR5),6990,Incineration,2019,2019,kt,156.443968,E,Estimated value
1832,GPP,Emissions from pre and post agricultural produ...,9,Oceania,723113,Emissions (CO2eq) (AR5),6990,Incineration,2020,2020,kt,156.214363,E,Estimated value
1833,GPP,Emissions from pre and post agricultural produ...,9,Oceania,723113,Emissions (CO2eq) (AR5),6990,Incineration,2021,2021,kt,157.124334,E,Estimated value
1834,GPP,Emissions from pre and post agricultural produ...,9,Oceania,723113,Emissions (CO2eq) (AR5),6990,Incineration,2022,2022,kt,157.502521,E,Estimated value
1835,GPP,Emissions from pre and post agricultural produ...,9,Oceania,723113,Emissions (CO2eq) (AR5),6990,Incineration,2023,2023,kt,157.625493,E,Estimated value

In [6]:
fao_stat["Item"].unique()

array(['Fertilizers Manufacturing', 'Pesticides Manufacturing',
       'Food Processing', 'Food Transport', 'Food Packaging',
       'Food Retail', 'Food Household Consumption', 'Solid Food Waste',
       'Domestic Wastewater', 'Industrial Wastewater', 'Incineration'],
      dtype=object)

In [8]:
fao = (fao_stat.groupby("Year", as_index=False)["Value"].sum())

fao

    Year         Value
0   1990  2.489106e+06
1   1991  2.656398e+06
2   1992  2.754739e+06
3   1993  2.798399e+06
4   1994  2.836511e+06
5   1995  2.973251e+06
6   1996  3.071837e+06
7   1997  3.128737e+06
8   1998  3.173642e+06
9   1999  3.239977e+06
10  2000  3.425256e+06
11  2001  3.526273e+06
12  2002  3.551801e+06
13  2003  3.672015e+06
14  2004  3.787872e+06
15  2005  3.880282e+06
16  2006  3.990989e+06
17  2007  4.139554e+06
18  2008  4.219778e+06
19  2009  4.235924e+06
20  2010  4.380274e+06
21  2011  4.491437e+06
22  2012  4.547328e+06
23  2013  4.727331e+06
24  2014  4.797685e+06
25  2015  4.793243e+06
26  2016  4.865529e+06
27  2017  4.872828e+06
28  2018  4.921118e+06
29  2019  4.932911e+06
30  2020  4.976914e+06
31  2021  5.154396e+06
32  2022  5.247759e+06
33  2023  5.248296e+06

In [10]:
fao.to_csv("fao.csv")